import type { ContentPageKey } from "./pages";

export interface HeadingDefinition {
  text: string;
  level: 2 | 3;
}

/** Exact line matches used to recover heading structure from approved content. */
export const PAGE_HEADINGS: Record<ContentPageKey, HeadingDefinition[]> = {
  home: [
    { text: "App Overview", level: 2 },
    { text: "App Information", level: 3 },
    { text: "What Is Bet939 Game APP?", level: 2 },
    { text: "Why Bet 939 Game Is Popular in Pakistan", level: 2 },
    { text: "Main Features of Game", level: 2 },
    { text: "Simple Mobile Dashboard", level: 3 },
    { text: "Multiple Game Categories", level: 3 },
    { text: "Account and Wallet System", level: 3 },
    { text: "Live Gaming Options", level: 3 },
    { text: "Mobile-Friendly Performance", level: 3 },
    { text: "Transaction History", level: 3 },
    { text: "Login Security", level: 3 },
    { text: "Promotion Section", level: 3 },
    { text: "Customer Support Access", level: 3 },
    { text: "Regular Updates", level: 3 },
    { text: "Available Games", level: 2 },
    { text: "Hot Games", level: 3 },
    { text: "Slots", level: 3 },
    { text: "Mini Games", level: 3 },
    { text: "Fishing Games", level: 3 },
    { text: "Live Games", level: 3 },
    { text: "Card Games", level: 3 },
    { text: "Sports", level: 3 },
    { text: "Bonuses and Rewards", level: 2 },
    { text: "New-User Reward", level: 3 },
    { text: "First-Deposit Bonus", level: 3 },
    { text: "Recharge or Repeat-Deposit Offer", level: 3 },
    { text: "Daily Login Reward", level: 3 },
    { text: "Referral Reward", level: 3 },
    { text: "Cashback", level: 3 },
    { text: "VIP and Activity Rewards", level: 3 },
    { text: "Event Promotions", level: 3 },
    { text: "How to Download Bet939 Game Online", level: 2 },
    { text: "Android", level: 3 },
    { text: "iPhone and iPad", level: 3 },
    { text: "Windows PC and Laptop", level: 3 },
    { text: "How to Register and Login", level: 2 },
    { text: "Registration", level: 3 },
    { text: "Login Process", level: 3 },
    { text: "How to Deposit and Withdraw Money", level: 2 },
    { text: "How to Deposit Money", level: 3 },
    { text: "How to Withdraw Money", level: 3 },
    { text: "Supported Wallets", level: 2 },
    { text: "JazzCash", level: 3 },
    { text: "Easypaisa", level: 3 },
    { text: "Bank Transfer", level: 3 },
    { text: "Bet939 Online Experience", level: 2 },
    { text: "Is Bet 939 Safe or Not?", level: 2 },
    { text: "Benefits", level: 2 },
    { text: "Possible Limitations", level: 2 },
    { text: "Responsible Gaming Tips", level: 2 },
    { text: "Our Honest Review", level: 2 },
    { text: "User Reviews", level: 2 },
    { text: "Overall User Rating", level: 3 },
    { text: "Share Your Experience", level: 3 },
    { text: "Frequently Asked Questions", level: 2 },
    { text: "Final Words", level: 2 },
  ],
  download: [
    { text: "APK Information", level: 2 },
    { text: "Bet939 Game Download Requirements", level: 2 },
    { text: "How to Download Bet939 Game APK", level: 2 },
    { text: "How to Install APK", level: 2 },
    { text: "How to Enable Unknown App Installation", level: 2 },
    { text: "How to Update Apk to the Latest Version", level: 2 },
    { text: "APK Permissions", level: 2 },
    { text: "Common Downloading Issues and Fixes", level: 2 },
    { text: "APK Not Installing", level: 3 },
    { text: "“App Not Installed” Error", level: 3 },
    { text: '"App Not Installed" Error', level: 3 },
    { text: "APK Parsing Error", level: 3 },
    { text: "Bet939 Download Is Slow", level: 3 },
    { text: "Safety Tips", level: 2 },
    { text: "Conclusion", level: 2 },
    { text: "Frequently Asked Questions", level: 2 },
  ],
  login: [
    { text: "How to Create an Account", level: 2 },
    { text: "Bet939 Game Login Steps", level: 2 },
    { text: "Common Bet939 Login Issues and Fixes", level: 2 },
    { text: "Password Forgotten", level: 3 },
    { text: "OTP Not Received", level: 3 },
    { text: "Incorrect Password Error", level: 3 },
    { text: "Account Temporarily Blocked", level: 3 },
    { text: "Security Tips", level: 2 },
    { text: "Frequently Asked Questions", level: 2 },
  ],
  deposit: [
    { text: "What You Need Before Making a Deposit", level: 2 },
    { text: "Payment Methods Available", level: 2 },
    { text: "JazzCash", level: 3 },
    { text: "Easypaisa", level: 3 },
    { text: "Bank Transfer", level: 3 },
    { text: "How to Deposit Money", level: 2 },
    { text: "Minimum and Maximum Deposit Limits", level: 2 },
    { text: "How Long Does a Deposit Take?", level: 2 },
    { text: "Deposit Is Pending", level: 2 },
    { text: "Money Sent but Balance Not Updated", level: 2 },
    { text: "Deposit Request Was Rejected", level: 2 },
    { text: "Deposit Bonus", level: 2 },
    { text: "Deposit Safety Tips", level: 2 },
    { text: "Conclusion", level: 2 },
    { text: "Frequently Asked Questions", level: 2 },
  ],
  withdrawal: [
    { text: "What You Need Before Withdrawal", level: 2 },
    { text: "Payment Methods Available for Withdrawal", level: 2 },
    { text: "JazzCash", level: 3 },
    { text: "Easypaisa", level: 3 },
    { text: "Bank Transfer", level: 3 },
    { text: "How to Withdraw Money from Bet939", level: 2 },
    { text: "Minimum and Maximum Withdrawal Limits", level: 2 },
    { text: "How Long Does a Withdrawal Take?", level: 2 },
    { text: "Withdrawal Is Pending", level: 2 },
    { text: "Withdrawal Was Rejected", level: 2 },
    { text: "Money Deducted but Not Received", level: 2 },
    { text: "Wrong Wallet Number Entered", level: 2 },
    { text: "Bonus Turnover Requirements", level: 2 },
    { text: "Withdrawal Password or OTP Problem", level: 2 },
    { text: "Withdrawal Safety Tips", level: 2 },
    { text: "Frequently Asked Questions", level: 2 },
    { text: "Conclusion", level: 2 },
  ],
  ios: [
    { text: "iOS App Information", level: 2 },
    { text: "App Details", level: 3 },
    { text: "Can I Download Bet939 Game for Iphone?", level: 2 },
    { text: "Requirements for iOS", level: 2 },
    { text: "How to Download Bet939 for iOS", level: 2 },
    { text: "How to Trust the Developer Profile", level: 2 },
    { text: "Common Issues and Fixes", level: 2 },
    { text: "App Icon Is Not Appearing", level: 3 },
    { text: "App Is Not Installing", level: 3 },
    { text: "Untrusted Developer Error", level: 3 },
    { text: "Unable to Verify App Error", level: 3 },
    { text: "App Opens and Closes Immediately", level: 3 },
    { text: "Stuck on Loading", level: 3 },
    { text: "How to Update App on iPhone", level: 2 },
    { text: "iOS Safety Tips", level: 2 },
    { text: "Conclusion", level: 2 },
    { text: "Frequently Asked Questions", level: 2 },
  ],
  pc: [
    { text: "Method 1: Online Access on Browser", level: 2 },
    { text: "Method 2: Use an Android Emulator", level: 2 },
    { text: "How to Install Through an Emulator", level: 3 },
    { text: "PC Security Tips", level: 2 },
    { text: "Conclusion", level: 2 },
    { text: "Frequently Asked Questions", level: 2 },
  ],
};

/** Sections that should render consecutive short lines as lists. */
export const LIST_SECTION_TITLES = new Set([
  "Bet939 Game Download Requirements",
  "How to Download Bet939 Game APK",
  "How to Install APK",
  "How to Enable Unknown App Installation",
  "How to Update Apk to the Latest Version",
  "APK Permissions",
  "Possible permissions can include:",
  "APK Not Installing",
  "Try these solutions:",
  "“App Not Installed” Error",
  '"App Not Installed" Error',
  "This error can appear because:",
  "Bet939 Download Is Slow",
  "A slow download can be caused by:",
  "Safety Tips",
  "How to Create an Account",
  "Bet939 Game Login Steps",
  "Password Forgotten",
  "OTP Not Received",
  "Account Temporarily Blocked",
  "A temporary restriction may happen because of:",
  "Security Tips",
  "What You Need Before Making a Deposit",
  "Keep the following things ready:",
  "How to Deposit Money",
  "Follow these general steps:",
  "Processing time can depend on:",
  "Common reasons include:",
  "Money Sent but Balance Not Updated",
  "If the payment does not appear, collect:",
  "Deposit Request Was Rejected",
  "A deposit request may be rejected because:",
  "Before claiming it, check:",
  "Check:",
  "Deposit Safety Tips",
  "What You Need Before Withdrawal",
  "Keep the following ready:",
  "Bank withdrawal require:",
  "How to Withdraw Money from Bet939",
  "Withdrawal Is Pending",
  "Withdrawal Was Rejected",
  "A request may be rejected because:",
  "Money Deducted but Not Received",
  "First, check:",
  "Bonus Turnover Requirements",
  "If the OTP does not arrive:",
  "Withdrawal Safety Tips",
  "Requirements for iOS",
  "Before starting the installation, check:",
  "How to Download Bet939 for iOS",
  "Follow these steps to download the game through Safari:",
  "When the iPhone shows an Untrusted Enterprise Developer message, follow these steps:",
  "App Icon Is Not Appearing",
  "If the app icon does not appear after approving the installation:",
  "App Is Not Installing",
  "The installation can fail because of:",
  "Unable to Verify App Error",
  "The “Unable to Verify App” message may appear when:",
  "Try these fixes:",
  "App Opens and Closes Immediately",
  "Try the following:",
  "How to Update App on iPhone",
  "When a new version is available:",
  "iOS Safety Tips",
  "Method 1: Online Access on Browser",
  "Common requirements include:",
  "How to Install Through an Emulator",
  "PC Security Tips",
  "Registration",
  "Follow these general steps to create an account:",
  "Login Process",
  "Registered users can access their accounts by following these steps:",
  "How to Deposit Money",
  "How to Withdraw Money",
  "Before starting a game:",
  "Benefits",
  "Possible Limitations",
  "Responsible Gaming Tips",
  "Hot Games",
  "Some available options include:",
  "Available Games:",
  "These games are available on platform.",
  "Available fishing providers include:",
  "Available live-game providers include:",
  "Available card-game providers include:",
  "Available sports providers include:",
  "First-Deposit Bonus",
]);
